### ISSUE TITLE
v0.12.2

### ISSUE THREAD

**Issue by 0x1eef** [ruby/uri#100]
It does not appear that v0.12.2 has been published to GitHub, and it appears that the fix in that version has not been applied to v0.13.0 (or master). I assume the changes to `lib/uri/rfc3986_parser.rb` in v0.12.2 should be applied to master and the v0.13.0 branch ?

**Comment by hsbt** [comment]
https://github.com/ruby/uri/releases/tag/v0.12.2 ?

**Comment by 0x1eef** [comment]
Thanks ! And sorry, I was looking for a more recent commit. Should the changes made to `lib/uri/rfc3986_parser.rb` be applied to v0.13.0 as well ? Otherwise, if I installed v0.13.0 on Ruby <=3.2.3, wouldn't the bug become an issue again ?

**Comment by 0x1eef** [comment]
My mistake. :) The fix for the bug is in v0.13.0: [commit](https://github.com/ruby/uri/commit/9d7bcef1e6ad23c9c6e4932f297fb737888144c8).  I guess the rest of the diff between v0.12.2 and v0.13.0 is related to a refactor.
