### ISSUE TITLE
using RFC_3986 with URI::Generic.build

### ISSUE THREAD

**Issue by alexanderfletcher** [ruby/uri#104]
With URI::Generic you can pass in a custom parser (or the in built RFC_3986 one). However build uses the default parser. Would it be possible to extend the `build` method to allow to pass a parser in?

It's also a bit confusing that the `parse` methods uses RFC3986 while the build method uses the older RFC2396

**Comment by gareth** [comment]
I made a patch to address this [on the ruby-lang bugs list](https://bugs.ruby-lang.org/issues/19266) a year ago, at the time I didn't realise that the URI library was maintained on Github.

I only just saw @jeremyevans' comment on that issue, so I'll port that patch over to Github tomorrow and submit it as a PR.
