### ISSUE TITLE
Provide `URI::RFC2396_PARSER` for Ruby 3.3 or older

### ISSUE THREAD

**Issue by yahonda** [ruby/uri#118]
This issue requests to provide `URI::RFC2396_PARSER` for Ruby 3.3 or older version because Ruby on Rails supports Ruby 3.1.0 and higher and I want to support these Ruby versions without if RUBY_VERSION clauses.

### Background

Ruby on Rails runs CI against Ruby master branch and it enables `RAILS_STRICT_WARNINGS=1` flag to let Rails CI fail if any warnings appeared.

Since https://github.com/ruby/ruby/commit/b41d79962abefbe8b70d76dee134b44a3a3d3929, Rails Ci against Ruby master branch is getting failed as expected. To address this warning, I have replaced `URI::DEFAULT_PARSER.escape` with `URI::RFC2396_PARSER.escape` as suggested. It works against Ruby master branch but it raises `uninitialized constant URI::RFC2396_PARSER (NameError)` against Ruby 3.3.4 that bundles uri version 0.13.0

### Steps to reproduce

$ irb -w
```
require 'uri'
URI::DEFAULT_PARSER.escape("/:controller(/:action)")
URI::RFC2396_PARSER.escape("/:controller(/:action)")
```

### Expected behavior
Ruby 3.3.4 runs these statements without successfully warnings.

### Actual behavior
It raises `uninitialized constant URI::RFC2396_PARSER (NameError)`

```ruby
$ ruby -v
ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]
$ irb -w
irb(main):001> require 'uri'
=> true
irb(main):002> URI::VERSION
=> "0.13.0"
irb(main):003> URI::DEFAULT_PARSER.escape("/:controller(/:action)")
=> "/:controller(/:action)"
irb(main):004> URI::RFC2396_PARSER.escape("/:controller(/:action)")
(irb):4:in `<main>': uninitialized constant URI::RFC2396_PARSER (NameError)

URI::RFC2396_PARSER.escape("/:controller(/:action)")
   ^^^^^^^^^^^^^^^^
Did you mean?  URI::RFC2396_Parser
               URI::RFC3986_Parser
               URI::RFC3986_PARSER
	from <internal:kernel>:187:in `loop'
	from /home/yahonda/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/exe/irb:9:in `<top (required)>'
	from /home/yahonda/.rbenv/versions/3.3.4/bin/irb:25:in `load'
	from /home/yahonda/.rbenv/versions/3.3.4/bin/irb:25:in `<main>'
irb(main):005>
```

Here is the result against Ruby 3.4.0dev, that works as expected.
```ruby
$ ruby -v
ruby 3.4.0dev (2024-08-22T23:47:40Z master fdba458e85) [x86_64-linux]
$ irb -w
Ignoring io-console-0.7.2 because its extensions are not built. Try: gem pristine io-console --version 0.7.2
Ignoring psych-5.1.2 because its extensions are not built. Try: gem pristine psych --version 5.1.2
Ignoring cgi-0.4.1 because its extensions are not built. Try: gem pristine cgi --version 0.4.1
Ignoring date-3.3.4 because its extensions are not built. Try: gem pristine date --version 3.3.4
Ignoring io-console-0.7.2 because its extensions are not built. Try: gem pristine io-console --version 0.7.2
Ignoring json-2.7.2 because its extensions are not built. Try: gem pristine json --version 2.7.2
Ignoring prism-0.30.0 because its extensions are not built. Try: gem pristine prism --version 0.30.0
Ignoring psych-5.1.2 because its extensions are not built. Try: gem pristine psych --version 5.1.2
irb(main):001> require 'uri'
=> true
irb(main):002> URI::VERSION
=> "0.13.0"
irb(main):003> URI::DEFAULT_PARSER.escape("/:controller(/:action)")
(irb):3: warning: URI::RFC3986_PARSER.escape is obsoleted. Use URI::RFC2396_PARSER.escape explicitly.
=> "/:controller(/:action)"
irb(main):004> URI::RFC2396_PARSER.escape("/:controller(/:action)")
irb(main):005>

**Comment by hsbt** [comment]
Make sense. I will plan to release to URI-0.12.3 and 0.13.1 with #119 and #120. After that, I will request to backport them to Ruby 3.2 and 3.3.

Is it enough to your use-case?

**Comment by yahonda** [comment]
> Is it enough to your use-case?

Current Rails main branch supports Ruby 3.1.0 and higher,
So it would be appreciateed if `URI::RFC2396_PARSER` is also available
for Ruby 3.1.

https://github.com/rails/rails/blob/c6e3336cfdec5ae9c7fb98b03d0196aa56ab30f9/rails.gemspec#L12

Once newer version of uri is available, we can add the uri as Active Support dependency.

https://github.com/rails/rails/blob/main/activesupport/activesupport.gemspec

**Comment by yahonda** [comment]
I meant to say I'm happy if the newer version of `uri` that supports Ruby 3.1+ is available at RubyGems, we can add this gem explicitly in the Active Support.

**Comment by hsbt** [comment]
This feature is not security fix, it's impossible to backport to Ruby 3.1 with our maintenance policy.

But URI-0.12.3 is also working Ruby 3.1. `s.add_dependency 'uri', '>= 0.12.3'` resolve the original issue.

**Comment by Earlopain** [comment]
Is there a problem with requiring the latest `uri` on all rubies? I for example already have `uri` through `faraday` => `net-http` => `uri` which just pulls in the latest version. Faraday itself supports ruby `>= 3.0`.

**Comment by hsbt** [comment]
I released https://github.com/ruby/uri/releases/tag/v0.12.3 and https://github.com/ruby/uri/releases/tag/v0.13.1. They are also released with next stable versions, see https://github.com/ruby/ruby/pull/11465 and https://github.com/ruby/ruby/pull/11466.

Q. Why we deprecate them?

A. I and @yahonda ask that to @nurse in this week. `URI.escape` and these deprecated methods can't parse multibyte URI correctly. We shouldn't use for that.

**Comment by yahonda** [comment]
Thank you for releasing the v0.12.3 and v0.13.1. Considering the current RubyGem dependency resolution, I think Rails need to add `v0.13.1` or higher version of uri.

**Comment by yahonda** [comment]
I'll open a pull request to rails/rails and will inform if there are some issues happens.

**Comment by yahonda** [comment]
> I'll open a pull request to rails/rails and will inform if there are some issues happens.

Opened https://github.com/rails/rails/pull/52779

**Comment by yahonda** [comment]
Closing this issue as https://github.com/rails/rails/pull/52779 has been merged to Rails main branch.
Thank you for providing the new version of uri.
