### ISSUE TITLE
Concerns 0.13.1

### ISSUE THREAD

**Issue by lparry** [ruby/uri#122]
Hey there,

`0.13.1` showed up in our CI today and caused us some teething issues which made us look a little closer and I noticed that `0.13.1` is not on the repo's releases page, while it is up on rubygems.

I then noticed there is a `0.13.1` tag, but it's not signed (while the `0.13.0` release was signed/verified).

Is this a legit release?

**Comment by hsbt** [comment]
>Is this a legit release?

Yes, see https://github.com/ruby/uri/releases/tag/v0.13.1

**Comment by lparry** [comment]
Thanks!
