### ISSUE TITLE
return unnecessary question mark when uri query is "" but not nil

### ISSUE THREAD

**Issue by lisbethw1130** [ruby/uri#13]
way to reproduce
```
uri = URI.parse('/aaa/bbb')
uri.query = ''
uri.to_s
```
should be: `/aaa/bbb`
it's now: `/aaa/bbb?`

**Comment by jeremyevans** [comment]
This isn't a bug, it's an implementation detail.  Set `uri.query = nil` if you don't want the question mark.

If `''` were treated the same as `nil`, then `URI.parse('/aaa/bbb?').to_s` would be `"/aaa/bbb"` instead of `"/aaa/bbb?"`.
