### ISSUE TITLE
`URI::REGEXP::PATTERN::IPV6ADDR` no longer available in 1.0.1

### ISSUE THREAD

**Issue by jordan-brough** [ruby/uri#131]
The [cookiejar gem](https://github.com/dwaite/cookiejar/tree/master/lib/cookiejar) used `URI::REGEXP::PATTERN::IPV6ADDR` and `URI::REGEXP::PATTERN:: IPV4ADDR` from uri versions < 1.0.0.

Now the library raises this exception:
```
uninitialized constant CookieJar::CookieValidation::PATTERN::IPV4ADDR
```

Because this code is failing:
```ruby
  module CookieValidation
    module PATTERN
      include URI::REGEXP::PATTERN
      ...
      IPADDR = "#{IPV4ADDR}|#{IPV6ADDR}".freeze
```
[see here](https://github.com/dwaite/cookiejar/blob/36332870693334ad9fb51dbfebc398b46bb1427a/lib/cookiejar/cookie_validation.rb#L28-L32).

Would it be possible to restore and deprecate those constants?  The cookiejar project is archived so replacing it will take some work.

**Comment by hsbt** [comment]
Thank you for your report.

How about https://github.com/ruby/uri/pull/132? That test-case covered your issues.

**Comment by jordan-brough** [comment]
Thank you for the quick response @hsbt! The update seems to be working for me.
