### ISSUE TITLE
Can't call escape method on Ruby 3.0.0

### ISSUE THREAD

**Issue by zacky1972** [ruby/uri#14]
I can't call `escape` method of `URI` on Ruby 3.0.0 as follows:

```bash
% ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
% irb
irb(main):001:0> p URI.espace('http://images.google.co.jp/images?q=モナリザ&ie=E
UC-JP')
Traceback (most recent call last):
        4: from /Users/zacky/.rbenv/versions/3.0.0/bin/irb:23:in `<main>'
        3: from /Users/zacky/.rbenv/versions/3.0.0/bin/irb:23:in `load'
        2: from /Users/zacky/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/irb-1.3.0/exe/irb:11:in `<top (required)>'
        1: from (irb):1:in `<main>'
NoMethodError (undefined method `espace' for URI:Module)
```

I feel it has some problems.

**Comment by hsbt** [comment]
It's intentionally removed at https://github.com/ruby/uri/commit/61c6a47ebf1f2726b60a2bbd70964d64e14b1f98

**Comment by zacky1972** [comment]
Oh, my gosh.

I use Middleman 4.3, which uses `escape` method of `URI`...

Is there an alternative?

**Comment by ioquatix** [comment]
# This method is obsolete and should not be used. Instead, use
     # CGI.escape, URI.encode_www_form or URI.encode_www_form_component
     # depending on your specific use case.

**Comment by davidelbe** [comment]
Use `CGI.escape` instead. FYI, your first comment tries to use `espace`which I guess just is a spelling error. 

While you are waiting for Middleman to be updated you could always monkeypatch the escape method in URI to use CGI.escape instead.

**Comment by GieziJo** [comment]
In case somebody else stumbles uppon this, using the latest github version of middleman instead of the default version fixed this for me. In your `Gemfile` change `gem 'middleman'` to
```
gem 'middleman', github: 'middleman/middleman'
```

**Comment by paulschreiber** [comment]
`ERB::Util.url_encode` worked better for me, as it used `%20` instead of `+` for spaces.

**Comment by vidurpunj** [comment]
yes method is missing in ruby 3.1.2 also solution is do a monkey patching.
under intializers foler of rails application add a file.
uri_escape.rb with code as below:
```
module URI
  def URI.escape(url)
    url
  end
end
```

**Comment by shunwen** [comment]
From this ruby issue https://bugs.ruby-lang.org/issues/17309 , this is how you can get the same behavior as the obseleted method: `URI::DEFAULT_PARSER.escape(str)`
