### ISSUE TITLE
Regression of `URI.parse` in 0.12.0

### ISSUE THREAD

**Issue by shioyama** [ruby/uri#47]
We noticed this issue bumping URI from 0.11.0 to 0.12.0:

```ruby
# ruby/uri 0.12.0
URI.parse("https://").host
#=> ""

# ruby/uri 0.11.0
URI.parse("https://").host
=> nil
```

The issue seems to be https://github.com/ruby/uri/commit/81263c9e94bd67ca01deee238842a88c2c8885f3. Is this an intentional change? If so it should be mentioned in the [release notes](https://github.com/ruby/uri/releases/tag/v0.12.0) for 0.12.0 no?

**Comment by casperisfine** [comment]
I believe this was intentional https://github.com/ruby/uri/commit/81263c9e94bd67ca01deee238842a88c2c8885f3

**Comment by hsbt** [comment]
It's intentional changes. I added entry to https://github.com/ruby/uri/releases/tag/v0.12.0
