### ISSUE TITLE
The 0.10.0 release has no associated tag and github release

### ISSUE THREAD

**Issue by deivid-rodriguez** [ruby/uri#7]
Could it be created?

**Comment by deivid-rodriguez** [comment]
@hsbt No big deal but would you mind tagging the release on github?

**Comment by hsbt** [comment]
Thanks for your reminder. I tagged at https://github.com/ruby/uri/releases/tag/v0.10.0 now.

**Comment by deivid-rodriguez** [comment]
Awesome thanks!!
