### ISSUE TITLE
URI.parse considers https://example.com/### invalid when browsers consider it valid

### ISSUE THREAD

**Issue by eshnil** [ruby/uri#8]
```
$ruby -v
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
```

I have a form with `<input type="url" required>` and in the backend, I try to extract the domain with `URI.parse(url).host`

A user was able to submit a value like `https://example.com/###` which passed the browser's validation check, but failed by `URI.parse` with this error:
```
        3: from /Users/helix/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
        2: from /Users/helix/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
        1: from /Users/helix/.rbenv/versions/2.7.1/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split'
URI::InvalidURIError (bad URI(is not URI?): "https://example.com/###")
```
You can try the browser's behavior at MDN's demo: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

This is what the MDN page says about validation:

The syntax of a URL is fairly intricate. It's defined by WHATWG's URL Living Standard ( https://url.spec.whatwg.org/ ) and is described for newcomers in our article What is a URL? ( https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL )

**Comment by jeremyevans** [comment]
Currently, `URI.parse` is `URI::RFC3986_PARSER.parse`, and this isn't valid in RFC 3986.  We would have to add `URI::WHATWG_PARSER` or something similar, and use that in `URI.parse`.  Worth mentioning is that `URI::DEFAULT_PARSER` uses the even older standard of RFC 2396.  Only `URI.{split,parse,join}` use `URI::RFC3986_PARSER`.

A good question is, is that URL valid according to the WHATWG URL standard.  Here's what the WHATWG URL standard states:

```
A URL-fragment string must be zero or more URL units.

The URL units are URL code points and percent-encoded bytes.

The URL code points are ASCII alphanumeric, U+0021 (!), U+0024 ($), U+0026 (&), U+0027 ('), 
U+0028 LEFT PARENTHESIS, U+0029 RIGHT PARENTHESIS, U+002A (*), U+002B (+), U+002C (,), 
U+002D (-), U+002E (.), U+002F (/), U+003A (:), U+003B (;), U+003D (=), U+003F (?), U+0040 (@), 
U+005F (_), U+007E (~), and code points in the range U+00A0 to U+10FFFD, inclusive, excluding
surrogates and noncharacters.
```

I don't see `#` (`U+0023`) listed, leading me to believe that `#` is not valid in URL fragments according to the WHATWG URL standard unless it is percent encoded.  As such, I think this is not a bug and the issue can be closed.  You may want to open a bug report with MDN or whatever browser is allowing `#` unencoded in fragments.
