### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by voxik** [ruby/uri#96]
The l[icense file](https://github.com/ruby/uri/blob/master/LICENSE.txt) containes BSD-2-Clause license, while  [gemspec](https://github.com/ruby/uri/blob/5e0661d48e27286891207021513fc312716e25b4/uri.gemspec#L19) specifies Ruby OR BSD-2-Clause. What is the correct information please?

**Comment by hsbt** [comment]
"Ruby OR BSD-2-Clause" is.

**Comment by voxik** [comment]
Thx. Now what is the right place to keep this information? Ruby has COPYING file referring to the BSD license (file). Is this the way to go?

**Comment by hsbt** [comment]
Fixed at https://github.com/ruby/uri/commit/e84670a9e2e0c40eba8d722c1b26929cd5bd6ce8
